[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
viaIR = true
optimizer = true
optimizer_runs = 200
gas_limit = 100000000000  # high gas limit for long-running tests

remappings = [
  "@forge-std/=lib/forge-std/src/",
  "@chainlink/=lib/chainlink/contracts/src/v0.8/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
